# Generated by Django 4.0 on 2022-05-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_card', models.CharField(max_length=60)),
                ('phone_type', models.CharField(max_length=90)),
                ('price', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Fashion Card',
                'verbose_name_plural': 'Fashion Cards',
            },
        ),
    ]
