# Generated by Django 4.0 on 2022-05-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_fashioncards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashioncards',
            name='title_card',
        ),
        migrations.AddField(
            model_name='fashioncards',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
