# Generated by Django 4.0 on 2022-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_fashioncards_title_card_fashioncards_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBackCovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_name', models.CharField(max_length=100)),
                ('cover_price', models.IntegerField(default=5)),
                ('cover_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Phone Back Cover',
                'verbose_name_plural': 'Phone Back Covers',
            },
        ),
    ]
