# Generated by Django 4.0 on 2022-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_phonebackcovers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories_name', models.CharField(max_length=100)),
                ('accessories_price', models.IntegerField(default=4)),
                ('accessories_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Phone Accessories',
                'verbose_name_plural': 'Phone Accessories',
            },
        ),
    ]
