# Generated by Django 4.0 on 2022-05-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTopCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_theme', models.CharField(max_length=100)),
                ('money', models.IntegerField(default=100)),
                ('users', models.IntegerField(default=100)),
                ('new_clients', models.IntegerField(default=100)),
                ('sales', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Dashboard Top',
                'verbose_name_plural': 'Dashboard Top Cards',
            },
        ),
    ]
