# Generated by Django 4.0 on 2022-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtopcards',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashboardtopcards',
            name='main_theme',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardtopcards',
            name='money',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='dashboardtopcards',
            name='new_clients',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='dashboardtopcards',
            name='sales',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='dashboardtopcards',
            name='users',
            field=models.FloatField(default=100),
        ),
    ]
