# Generated by Django 4.0 on 2022-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_dashboardtopcards_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtopcards',
            name='main_theme',
            field=models.CharField(max_length=100),
        ),
    ]
