# Generated by Django 4.0 on 2022-05-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
